### ISSUE TITLE
question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [DP-Hridayan/aShellYou#205]
For today's release, our scanners reported:

```
! repo/in.hridayan.ashell_51.apk declares sensitive permission(s):
  android.permission.MANAGE_EXTERNAL_STORAGE android.permission.REQUEST_INSTALL_PACKAGES
```

Could you please clarify for what those are used? In the release notes, I see you've added an in-app updater. Is that strictly opt-in and informs about the implications? From the [IzzyOnDroid App Inclusion Policy](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Inclusion-Policy):

> [an app] must not download additional executable binary files (e.g. addons, auto-updates, etc.) without explicit user consent. Consent means it needs to be opt-in (it must not be harder to decline than to accept or presented in a way users are likely to press accept without reading) and structured in a way that clearly explains to users that they’re choosing to bypass the checks performed in this repo if they activate it.

Same paragraph exists in the inclusion criteria at F-Droid.org. So if those are not met, we'll unfortunately have to remove aShellYou from IzzyOnDroid, [where it is listed](https://apt.izzysoft.de/packages/in.hridayan.ashell) since 2024-03-18 (so almost exactly for 1 year now).

**Comment by DP-Hridayan** [comment]
The install packages option is there to allow users to install the latest
updated version from the github repository directly without visiting the
site. I downloads and allow users to quickly update the app and it is
mentioned in the app updater panel. Also there is no auto update feature,
users can choose to turn on "Auto update checker" which is turned off by
default. This feature allows users to detect an update but never auto
installs it. Users have to click download button to get the latest version
which is mentioned!

**Comment by DP-Hridayan** [comment]
Also I forgot to mention that the MANAGE_EXTERNAL_STORAGE permission is to
push/ pull files from other devices which are connected to the device using
aShell You via Wireless Debugging feature.

If you have any suggestions or improvements that I need to make, please let
me know!

**Comment by IzzySoft** [comment]
> The install packages option is there to allow users to install the latest updated version from the github repository directly without visiting the site. I downloads and allow users to quickly update the app and it is mentioned in the app updater panel. Also there is no auto update feature, users can choose to turn on "Auto update checker" which is turned off by default. This feature allows users to detect an update but never auto installs it. Users have to click download button to get the latest version which is mentioned!

Good that it's opt-in – otherwise it would violate the [IzzyOnDroid App Inclusion Policy](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Inclusion-Policy) as well as F-Droid's, which has the exact same item in it:

> [the app] must not download additional executable binary files (e.g. addons, auto-updates, etc.) without explicit user consent. Consent means it needs to be opt-in (it must not be harder to decline than to accept or presented in a way users are likely to press accept without reading) and structured in a way that clearly explains to users that they’re choosing to bypass the checks performed in this repo if they activate it.

So before enabling it (for the first time), is there information shown about the implications (i.e. that it would skip the extra screening performed by IzzyOnDroid/F-Droid)? You know we run a couple of extra scans to make sure all is fine (as this issue shows: it was one of those scans bringing these two extra permissions to our attention).

> Also I forgot to mention that the MANAGE_EXTERNAL_STORAGE permission is to push/ pull files from other devices which are connected to the device using aShell You via Wireless Debugging feature.

Thanks! Added that straight to the app's "green list" with the description, so it is now shown in our repo browser. Will do the same for the install permission as soon as we've clarified that.

**Comment by DP-Hridayan** [comment]
The Auto Check for Update option is turned off by default. And when the
user manually checks for update then this popup will appear when new
version is available. It will ask the user to download the latest version .
Only then if the user choose to download, the latest apk from github will
be downloaded and prompt user to install the latest apk for which the
Install from unknown sources permission is needed! This similar feature is
already on other fosss apps so I , too , decided to add it for user
convenience!

Tell me if it needs any improvements.

**Comment by IzzySoft** [comment]
Convenience yes – but still violating the inclusion policy, as the implications (bypassing the additional screening) are not made clear. Could you integrate e.g. a popup message on first activation, clearly stating these implications and asking if Github updates should really be activated? Something like "… Note that downloading updates from Github bypasses additional screenings performed by e.g. IzzyOnDroid …"? Not sure where else aShellYou is available, so you might wish to fill that in as well.

I haven't seen your current popup, so it's hard to compare.

**Comment by DP-Hridayan** [comment]
ok I will add a popup dialog now upon pressing the download button.
It will be something like :
"You're about to download updates directly from GitHub. Unlike updates from
app stores, these are not reviewed for security. Do you want to continue?"

**Comment by DP-Hridayan** [comment]
Is this good? It appears when user clicks the download button!

**Comment by DP-Hridayan** [comment]
![Image](https://github.com/user-attachments/assets/8f01511a-08a8-4586-8e42-a6fdfa3d11d5)
![Image](https://github.com/user-attachments/assets/d000d73c-33e6-4b51-958b-c34ddbde9ba3)

**Comment by IzzySoft** [comment]
That would be fully sufficient, yes – thanks! Once that's in place, I'd add the permission to the app's "green list" with the proper explanation.

**Comment by DP-Hridayan** [comment]
Thanks! I have already pushed the update.

Btw I am sorry for troubling you but I have updated the screenshots but they were not reflected in the izzy droid repo of aShell You. I have kept the format same as before , i.e., .jpeg.

**Comment by IzzySoft** [comment]
> Thanks! I have already pushed the update.

Thanks! Just missed today's sync, so that will go live with the next one then (sync runs every 24h).

>  I have updated the screenshots but they were not reflected in the izzy droid repo of aShell You

were they not? To me it looks they were:

![Image](https://github.com/user-attachments/assets/581def19-3886-4043-93ad-e69b52c321c2)

Maybe you need to refresh your browser (or try an incognito window) to check?

**Comment by DP-Hridayan** [comment]
Oh it was a browser caching issue , its updated thanks! I will close the issue now .

**Comment by DP-Hridayan** [comment]
>and give you some in return on the changelog: Fastlane limits their sizes to 500 chars max, everything else is being cut off – even mid-word, at exactly that position

Thanks for the info, I will keep that in mind for future changelogs!

**Comment by DP-Hridayan** [comment]
@IzzySoft Can I ask you a question? In fastlane I have 12 screenshots and the issue is screenshots `10.jpeg`, `11.jpeg`  &  `12 .jpeg` comes after `1.jpeg`. It is to be expected but I wondered if I can fix it? Will adding 0 before single digits work? is it allowed?

**Comment by DP-Hridayan** [comment]
@IzzySoft  Got it! But I think I will need you to handle existing single digit `jpeg`s since adding `0` before single digits will count them as separate right? So after I push the new ones with 0 in front handle any duplicates if any remain that is 😁

**Comment by DP-Hridayan** [comment]
Got it! Thanks for the clarification.

**Comment by DP-Hridayan** [comment]
@IzzySoft Hey buddy, I had bit of a query! 
I have a `Backup & Restore` feature in `aShellYou`.  You can use it to backup settings and database locally but recently I added the option to sign in with `Google` and backup to `Google Drive` using `drive scope for app data`. So is it like allowed in `Froid` policies? It is an `opt-in` feature btw, and doesn't limit anything even if user doesn't use it!

**Comment by IzzySoft** [comment]
Depends on how it's implemented. Doesn't Drive require GMS? That would be a deal-breaker then (though you might wish to see our [Replacing proprietary libraries](https://izzyondroid.org/docs/devpractices/ProprietaryLibraries/), follow up to the microG implementation matrix, and see that it might offer you a path to avoid Google's proprietary libs).

Alternatively, [build flavors](https://developer.android.com/build/build-variants) are your friends…

**Comment by DP-Hridayan** [comment]
I see! Thanks for the advice. I will do the research.

**Comment by DP-Hridayan** [comment]
@IzzySoft I have adopted Fdroid flavour which doesn't include the cloud backup and any  libraries! Do I need to do anything in fdroid meta data for them to build the fdroid flavour?

**Comment by IzzySoft** [comment]
Not only for them – for us, too; else RB will fail, and your APKs might not even be picked up.

* what will the file names at the releases be then?
* F-Droid also needs to be informed that they need to build the `fdroid` flavor

```yaml
Binaries: 
  https://github.com/DP-Hridayan/aShellYou/releases/download/%v/aShellYou-%v-release.apk

Builds:
  - versionName: v7.1.0
    versionCode: 58
    commit: 56f54626ecab7ace12f1002e3e32a25abd128129
    subdir: app
    gradle:
      - yes
    scandelete:
      - build-logic/convention/build
```

here, `gradle: yes` needs to be changed to `gradle: fdroid` then (at F-Droid) – and probably also the `Binaries`, unless you keep that name for the `fdroid` flavor. Similarly, at our end we need to adjust `apk_pattern` and the `gradlew` call accordingly:

```yaml
  - tag: v7.1.0
    apks:
      - apk_pattern: aShell\.?You.*-release\.apk
        apk_url: https://github.com/DP-Hridayan/aShellYou/releases/download/v7.1.0/aShellYou-v7.1.0-release.apk
        build:
          - chmod +x gradlew
          - ./gradlew assembleRelease
```

**Comment by DP-Hridayan** [comment]
Thanks for answering! I will do it before release then.

**Comment by DP-Hridayan** [comment]
@IzzySoft The apk uploaded to Github releases will have this same name pattern 
> Binaries: 
  https://github.com/DP-Hridayan/aShellYou/releases/download/%v/aShellYou-%v-release.apk

The apk generated by `./gradlew assembleFdroidRelease` will be available at `app/build/outputs/apk/fdroid/release` with the name `app-fdroid-release.apk`.

The apk uploaded to github releases will be the `github` flavour. 

Can you also tell me how do I notify `Fdroid` of the changes?

**Comment by IzzySoft** [comment]
> The apk uploaded to Github releases will have this same name pattern

OK

> The apk generated by `./gradlew assembleFdroidRelease` will be available at `app/build/outputs/apk/fdroid/release` with the name `app-fdroid-release.apk`.
> 
> The apk uploaded to github releases will be the `github` flavour.

🤪 So we put cherries next to the tomatoes and hope for cherry tomatoes? 🙈 OK, the missing link: "The APK at releases is build using `assembleGithubRelease`". Correct? And while we're on it:

```gradle
            signingConfig = signingConfigs.findByName("release")
                ?: signingConfigs.getByName("debug")
```

Very bad idea. One does not sign a release build with a debug key. Can you please change that to e.g.

```gradle
            signingConfig = signingConfigs.findByName("release")
                ?: null
```

Otherwise RB will fail. We need to build an unsigned APK.

> Can you also tell me how do I notify `Fdroid` of the changes?

Open an issue or MR with them at their fdroiddata repository, I'd say.

**Comment by DP-Hridayan** [comment]
I can just do this right ?
>             signingConfig = signingConfigs.findByName("release")

Android studio is suggesting to remove the null!

**Comment by DP-Hridayan** [comment]
@IzzySoft  Is there something that needs fixing in the metadata in fdroid data? Or do I need to upload fdroid flavopur apk to github releases
```
Categories:
  - System
License: GPL-3.0-or-later
AuthorName: DP Hridayan
AuthorEmail: hridayanofficial@gmail.com
SourceCode: https://github.com/DP-Hridayan/aShellYou
IssueTracker: https://github.com/DP-Hridayan/aShellYou/issues

AutoName: aShell You

RepoType: git
Repo: https://github.com/DP-Hridayan/aShellYou.git
Binaries: 
  https://github.com/DP-Hridayan/aShellYou/releases/download/%v/aShellYou-%v-release.apk

Builds:
  - versionName: v7.1.0
    versionCode: 58
    commit: 56f54626ecab7ace12f1002e3e32a25abd128129
    subdir: app
    gradle:
      - yes
    scandelete:
      - build-logic/convention/build

  - versionName: v7.2.0
    versionCode: 59
    commit: 2ce656180c419f5dfb4f360d05990b5f2a77dd41
    subdir: app
    gradle:
      - fdroid

AllowedAPKSigningKeys: dc4217203a7284bd159d7b863b7990620069c7929d6f5a51f59a321e77f18d4c

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: v7.2.0
CurrentVersionCode: 59
```
